---
name: Build, test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# GO check for nil checker exceptions with tool thing
# TODO:
# https://olegk.dev/github-actions-and-go

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # just in case ¯\_(ツ)_/¯

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go vet ./...

      - name: Run tests
        run: go test ./...
